### ISSUE TITLE
(Cards screen) - pretvoriti 4 velika u jedan div koji se poziva više puta iz @foreach

### ISSUE THREAD

**Issue by TommyEmmanuel** [eugendeur1/PersonalFinanceApp#1]
Sad trenutno ne možemo imati manje od 4 kartice, ovako nam to omogućava da imamo proizvoljan broj kartica

**Comment by TommyEmmanuel** [comment]
@eugendeur javi kad budeš gotov

**Comment by eugendeur1** [comment]
@TommyEmmanuel Gotov sa karticama i table i sumom count u table.

**Comment by eugendeur1** [comment]
Pozdrav Tomislav, 

Evo gotov sam s oba zadatka stavio sam komentar u github-u, pošto prvi put šaljem komentar pa nisam siguran da sam dobro to napravio pa javljam tu.
Sad cu ova dva dana proucavat  forme u Razoru.

**Comment by eugendeur1** [comment]
@TommyEmmanuel imam jedno pitanje npr korisnik ima 4 kartice ili 3 ili 1 ili 2 nebitno, to je sve zapisano pod njegov npr ID u nekoj bazi podataka i u tim slucajevima stavljamo nekakav uvijeti id = broju kartica koliko će ih se izraditi i kad dode do tog broja petlja prestaje raditi?
