### ISSUE TITLE
Dovršiti submit formu i filtere na karticama

### ISSUE THREAD

**Issue by TommyEmmanuel** [eugendeur1/PersonalFinanceApp#3]
1. preseliti MyTransaction u DbTables
2. isprogramirati Cards tako da radi year=0 i visa=true/false 
3. <style> preseliti u zaseban file i referenicirati file preko link taga
4. čišćenje
5. dodati sve godine 2022-2023 kao a tag i ukrasiti kao tagbox (kao button sa zaobljenim rubovima)
6. dodati dropdown za visa ili ne
7. uzeti ProfileFormData i izvući van u MyProfile klasu (treba ju dodati) i nakon toga dodati taj novi podatak u DbTables.UserProfiles
----> svaki put kad spremiš podatak, prebrišeš stari
----> posljednje spremljene podatke ćemo prikazati na vrhu iznad forme, u formatu (Eugen Deur, eugen.deur@gmail.com (0912226666) Lokacija...)

**Comment by eugendeur1** [comment]
@TommyEmmanuel gotov sam s svim zadatcima naišao sam na problem u zadnjem zadatku pa sam prvu liniju coda uzeo sa chat gpt a to je "<p>@Model.ime_prezime, @Model.email, @Model.telefon, @Model.lokacija, @Model.jezik </p>" i još jednu stvar sam uzeo sa chat gpt "if (ModelState.IsValid)" a sve ostalo sam napravio bez problema. Čišćenje ću napraviti sutra jer sam se danas fokusirao na sve zadatke. Ako close napravis onda je sve dobro jel tako?
