### ISSUE TITLE
Submit forma i validacije, kartice filteri

### ISSUE THREAD

**Issue by TommyEmmanuel** [eugendeur1/PersonalFinanceApp#4]
1. Urediti error.cshtml  tako da pošaljemo poruku korisniku što je pogriješio - proširenje modela od Error.cshtmla
2. Napraviti validacije na svim poljima 
- ništa ne smije bit prazno
- Ime prezime ne smije biti preko 30 znakova
- email mora biti u email formatu - u ifu provjeriti jel s lijeve i desne strane @ znaka ima nešto
- ako je odabrana hrvatska u listi država, obavezno početi s nulom

3. Kartice
- filteri moraju ostati od prethodnog filtriranja
- dodat filter sa slobodnim unosom (textbox) - svaka kartica koja sadrži taj tekst u bilo kojem od svojih propertija ostaje u zaslonu, ostale idu van
- - highlightat gdje se nalazi u tekstu

4. Započet rad na Proračunu
- Proračun mora biti dio dbtablesa
- Lista/tablica poput transakcija
- u bazi se inicijalno nalaze 3 proračuna (za 5, 6 i 7 ) - mjeseci su ne brojačni, nego tekstualni (siječanj, veljača itd)
- Proračun mora imati - Id, dopušteni budžet. za koji mjesec, i za koji odjel
- Ispod tablice se može unijeti novi budget sa 3 polja ( budžet je int, mjesec je enum :D, odjel je enum)
- Glavna validacija - ne smiješ unijeti budget za isti mjesec više puta
- Svaki put kad se osvježi stranica, redosljed osvježiti tako da je na vrhu najnoviji mjesec, a na dnu najstariji

Podsjetnik za idući put - modalni prozor

**Comment by eugendeur1** [comment]
@TommyEmmanuel Ej Tomislav rješio sam 1,2 i 3 zadatak i danas krećem s 4 zadatkom, naišao sam na problem di mi se javljala jedna pogreška i 1 warning ali uopće nisu dio coda koje sam ja pisao nego nešto 10, i puno puta mi se ne osvježava i dosta toga a error koji mi se pojavljuje ¸" <CreateAppHost AppHostSourcePath="$(AppHostSourcePath)" i citao sam sta da napravim te sam sam ispocetka clonirao iz gita project i dopisao codove iste s tog di imam gresku i na tom novome kao i na starome pokazuje warrning "<NETSdkWarning ResourceName="TargetFrameworkIsEol" ali bez error-a. Isto tako mi se i na tome novome pojavio error te sam pokrenuo project "run as adinistrator" i pocelo je raditi nadam se da je okej da nastavim raditi na tom clone i da ovaj samo maknem jer gubim vrijeme da maknem nešto što ni ne postoji

**Comment by eugendeur1** [comment]
@TommyEmmanuel  Napravio sam sva 4 zadatka. Java script za zadnji zadatak je bio problemcic jer sam numerirao u js a ne u controleru sa alert porukom koja se pojavi ko pop up kada se unese ili isti mjesec ili pod budzet se unese nesto što nije broj  sa porukom sta su pogrijesili. 1. zadatak error page sam napravio samo s error new message koji zaprima ako neki od if uvijeta u profilu kod validacije nije točan . U 3. Zadatku pod broj 1. Filteri moraju ostati od predhodnog to sam pokušao napraviti i tražio sam odgovor ali nisam uspio dokučiti što tu treba promjeniti vjerovatno nešto sa JS i html samo ali nisam uspio to naći. Zadatak broj 3 ostatak sam uredio i napravio vjerovatno točno i isto tako sam dodao izgled odabira kartice kao i na youtubu ispod searchbar.
