### ISSUE TITLE
Modalni prozori

### ISSUE THREAD

**Issue by TommyEmmanuel** [eugendeur1/PersonalFinanceApp#5]
Cards
-> search mora biti isto dio forme i filtrirati one kartice koje imaju zadovoljeni kriterij
-> dovršiti filter na tipu kartice da ostane zapamćen po uzoru na All years
--> kad se hovera mišem preko kartice, više nije stardardni kursor (strelica) nego je onaj click pointer
--> kad se klikne na karticu, onda se podiže novi modalni prozor aka popup
---> u modalnom prozoru imamo osim postojećih podataka i podatke sa pozadine kartice (CVV 3znamenkasti broj i ostalo)
---> napraviti jednostavni modalni prozor tako što je hidean u htmlu na dnu cshtmla i show-at ga kak se desi klik
---> kad se klikne (x) u desnom gornje kutu modalnoga prozora, onda se modalni hide-a
ovo sve gore vrijedi za prve tri kartice
za 4 karticu nećemo raditi vlastiti modalni, nego ćemo iskoristiti bootstrap modalni

Validacija Profila
-> dodati if null za sve stringove koji ulaze unutra
Proračun
-> kad se stisne na [Detalji] button od redtka, ide se na novu stranicu "ProracunRedak.cshtml" u kojem imamo  još detaljnije podatke o proračunu za taj odabrani redak
---> ti dodatni podaci su tko je tražio proračun, datum odobrenja proračuna, krajnji datum korištenja proračuna
---> ta nova stranica se mora otvoriti na temelju ID-a retka
---> to riješiti po uzoru na kartice gdje je query string npr ?ID=3
-> u zaslonu proračuni, u tablici, dodati novi stupac koji je obriši redak stupac [Obriši] button
---> obriši button mora brisati i iz baze, submit button po uzoru na add button (jedini dio forme koji se šalje na server je ID od retka)

EDIT proračuna
-> postojeće znanje o modalnom prozoru iskoristiti za ovaj task
--> dodati stupac sa button Edit
--> kad se stisne button edit na nekom retku, otvoriti modalni prozor koji ima formu  poput ove
![image](https://github.com/eugendeur1/PersonalFinanceApp/assets/14109046/58406dd5-e1af-405d-a83a-2658d140fc28)

ali sa popunjenim postojećim podacima

**Comment by TommyEmmanuel** [comment]
https://app.pluralsight.com/library/courses/c-sharp-10-fundamentals/table-of-contents

**Comment by eugendeur1** [comment]
@TommyEmmanuel ej Tomislav gotov sam s svime imat cu dva pitanja kad se vidimo a to je 1. brisati i iz baze i 2. 4 karticu nećemo raditi vlastiti modalni, nego ćemo iskoristiti bootstrap modalni(ako ne uspijem skuziti do sutra )
Sve sam uspio napraviti 90% toga sam napravio sam jedino Edit sam se poslužio internetom, zbog ovog zapisa if (!string.IsNullOrEmpty(searchText))
{
    allCardsFromDb = allCardsFromDb.Where(card =>
        card.FullName.Contains(searchText) ||
        card.CardNumber.ToString().Contains(searchText) ||
        card.ExpirationDate.ToString().Contains(searchText)
    ).ToList();
}
sam skuzio o cemu si pricao i detaljno sam ga prošao i uspio sam ga sam napisati.
Lp
